### ISSUE TITLE
V6.0 Not available in NuGet

### ISSUE THREAD

**Issue by JoniSykes** [chroma-sdk/Colore#249]
Wiki shows installation and usage of a V6.0 which doesn't appear to exist...

**Comment by theyuvalraz** [comment]
Yes but there are directions to how to download the v6 version in the wiki

**Comment by Sharparam** [comment]
Getting a release on NuGet for v6.0 is going slower than anticipated due to time constraints. Development builds are available on [MyGet](https://www.myget.org/feed/chroma-sdk/package/nuget/Colore) and should be reasonably stable.

The URLs in the "Getting Started" wiki page were apparently outdated so I updated them to point to the new MyGet organization.
