### ISSUE TITLE
Is it possible to run Colore without Synapse?

### ISSUE THREAD

**Issue by DominikDitoIvosevic** [chroma-sdk/Colore#260]
Would it be possible to just take some dlls and control my Chroma devices without having the full Synapse app installed on my pc using Colore library?

**Comment by Sharparam** [comment]
Colore relies on the Razer SDK files being installed on your system to run. These files used to be provided in an installer separate to the Synapse installer, but are now only provided by Synapse.

In theory you should be able to install Synapse somewhere once, copy the Razer SDK DLL files to another computer, and run SDK software there.

Since this method of installation isn't supported by Razer themselves, we would probably hesitate to handle bug reports regarding such installations unless they can be shown to appear on systems with the SDK installed as suggested by Razer. Thas is on a case-by-case basis of course and if we can see that the installation method is unrelated to the bug we'd be happy to provide support/fixes, but be aware that we might ask you to reproduce the problem on a supported system first.

**Comment by DominikDitoIvosevic** [comment]
I'm totally ok with this not being an officially supported scenario, I was just wondering if it's possible at all. Would this work though since I need to be logged in to Razer use Colore apparently. I've built a simple color picker and when I log out of razer it stops working and when ai log back in it works. Is there a way to avoid having to be logged in?
